"""driver on telemetry, alert resolution and notification fields

Revision ID: 207795249c72
Revises: 8b20d7fcdc08
Create Date: 2026-10-04 16:42:25.745150

Hand-adjusted from the autogenerated version:
  * new alert types: PostgreSQL stores enums as a native type, which needs ALTER TYPE ... ADD
    VALUE; SQLite stores them as VARCHAR sized to the longest value, so the column is widened
    ("battery_check_due" is longer than the previous longest value);
  * foreign keys get explicit names, which batch mode (SQLite) requires.
"""

import sqlalchemy as sa
from alembic import op

revision = "207795249c72"
down_revision = "8b20d7fcdc08"
branch_labels = None
depends_on = None

NEW_ALERT_TYPES = ("service_due", "brake_inspection", "battery_check_due", "device_offline")
ALL_ALERT_TYPES = (
    "low_battery",
    "battery_overheat",
    "battery_degraded",
    *NEW_ALERT_TYPES,
)


def upgrade():
    if op.get_bind().dialect.name == "postgresql":
        # ADD VALUE can't run inside a transaction block on older PostgreSQL versions.
        with op.get_context().autocommit_block():
            for value in NEW_ALERT_TYPES:
                op.execute(f"ALTER TYPE alert_type ADD VALUE IF NOT EXISTS '{value}'")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resolved_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("resolution_note", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("notified_at", sa.DateTime(), nullable=True))
        if op.get_bind().dialect.name != "postgresql":
            batch_op.alter_column(
                "alert_type",
                existing_type=sa.VARCHAR(length=16),
                type_=sa.Enum(*ALL_ALERT_TYPES, name="alert_type"),
                existing_nullable=False,
            )
        batch_op.create_foreign_key(
            "fk_alerts_resolved_by_id_users", "users", ["resolved_by_id"], ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("driver_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_telemetry_driver_id"), ["driver_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_telemetry_driver_id_users", "users", ["driver_id"], ["id"], ondelete="SET NULL"
        )


def downgrade():
    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.drop_constraint("fk_telemetry_driver_id_users", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_telemetry_driver_id"))
        batch_op.drop_column("driver_id")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_alerts_resolved_by_id_users", type_="foreignkey")
        batch_op.drop_column("notified_at")
        batch_op.drop_column("resolution_note")
        batch_op.drop_column("resolved_by_id")
    # PostgreSQL can't drop enum values; the extra alert types remain unused after a downgrade.
